### PR TITLE
Register team SkullR1d3r5

### PR DESCRIPTION
**Pull request by sql3t0**

### CODE REVIEW

**Comment by eltci** [comment]
Sorry. A failure has occurred when processing your proposal. Please contact support and present the following info:

**Stream name**: 2017/10/17/[$LATEST]b6c75be31ae749959fbf2bc9148f7579
**Request ID**: d48dd86d-b354-11e7-9450-53e47072c1eb

**Comment by thotypous** [comment]
@sql3t0 A user can only be part of at most one team. If you lost the `team-secrets.json` for the Th3v01d3 team, you need to contact the CTF staff to ask for support.

**Comment by sql3t0** [comment]
but i get out of a team and need  join me in other
how do I do that

2017-10-17 17:25 GMT-03:00 Paulo Matias <notifications@github.com>:

**Comment by alissonb** [comment]
We can exclude old team?

**Comment by sql3t0** [comment]
Yes !!

2017-10-17 21:57 GMT-03:00 gnx <notifications@github.com>:

**Comment by thotypous** [comment]
@sql3t0 the Th3v01d3 team was removed. Now you may try to register SkullR1d3r5 again. Please remove the `submissions` directory from your client and run `./ctf init` again. Thanks!

**Comment by sql3t0** [comment]
Thank man !! \m/

2017-10-18 9:04 GMT-03:00 Paulo Matias <notifications@github.com>:

**Pull request closed without merging**
